name: Production Release
description: Automated build and submission to App Store on main branch

on:
  push:
    branches: [main]
    
jobs:
  build_and_submit_ios:
    name: Build iOS and Submit to App Store
    type: build
    params:
      platform: ios
      profile: production
      auto_submit: true
      submit_profile: production
      
  build_android:
    name: Build Android Production
    type: build
    params:
      platform: android
      profile: production
      
  notify_success:
    name: Notify on Success
    type: custom
    depends_on:
      - build_and_submit_ios
      - build_android
    steps:
      - run: echo "✅ Production builds completed successfully!"
      - run: echo "iOS build submitted to App Store Connect"
      - run: echo "Android build ready for Google Play submission"